name: Fortify on Demand Scan

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    - cron: '16 9 * * 0'

jobs:
  FoD-SAST-Scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Fortify AST Scan
        uses: fortify/github-action@v2.1.1
        with:
          sast-scan: true
